(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const views=['homeView','quizView','resultsView','practiceView','momentsView'];
const clamp=n=>Math.max(0,Math.min(100,n));
function show(id){views.forEach(v=>{const e=$('#'+v);if(e)e.hidden=v!==id});$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.nav===id.replace('View','')));window.scrollTo({top:0,behavior:'smooth'})}
function header(t,s){$('#pageTitle').textContent=t;$('#pageSub').textContent=s}
function home(){show('homeView');header('Welcome to the messy middle.','This starts with you, then moves into real supervisor moments.')}
function practice(k='late'){show('practiceView');header('Your first rep','Try the conversation. Notice what your response makes easier or harder next.');loadScenario(k)}
function moments(){show('momentsView');header('Supervisor modules','Real responsibility, practiced before the live moment.')}

const quiz=[
{tag:'POWER',q:'A staff member challenges your decision in front of the whole team.',c:'Everyone looks at you. What pulls at you first?',a:[['Explain why the decision makes sense.',{urgency:2,control:4,approval:0,curiosity:-2,courage:1},'You moved toward certainty and authority.'],['Ask what they are seeing that you may be missing.',{urgency:0,control:-1,approval:0,curiosity:4,courage:3},'You made room for information without giving up your role.'],['Say you will talk privately later.',{urgency:1,control:2,approval:2,curiosity:0,courage:0},'You contained the moment, but postponed the disagreement.'],['Move the meeting along and circle back another day.',{urgency:1,control:1,approval:3,curiosity:-1,courage:-3},'You lowered discomfort, but delayed the hard part.']]},
{tag:'ACCOUNTABILITY',q:'Someone you supervise is late. Again.',c:'The team has had to cover. You already have the corrective action form open.',a:[['Start with the documented pattern and consequence.',{urgency:3,control:4,approval:-1,curiosity:-3,courage:2},'You prioritized consequence before context.'],['Name the pattern and impact, then ask what is happening.',{urgency:0,control:0,approval:0,curiosity:4,courage:4},'You held accountability and curiosity together.'],['Give one more chance because life is hard.',{urgency:-1,control:-1,approval:4,curiosity:1,courage:-3},'You protected the relationship from discomfort, but softened the expectation.'],['Tell them the team is tired of picking up their slack.',{urgency:3,control:3,approval:-2,curiosity:-4,courage:1},'You made impact visible, but used blame to do it.']]},
{tag:'ARMOR',q:'Halfway through a meeting, you realize your plan may be wrong.',c:'You are the person who recommended it.',a:[['Say what changed your thinking and adjust.',{urgency:0,control:-2,approval:-1,curiosity:3,courage:4},'You tolerated being visibly wrong and changed course.'],['Stick with it until you can reconsider privately.',{urgency:1,control:4,approval:1,curiosity:-3,courage:-2},'You protected authority and certainty.'],['Explain your original reasoning so everyone understands.',{urgency:1,control:2,approval:2,curiosity:-1,courage:0},'You protected your intent before fully addressing new information.'],['Ask the room what they think before deciding.',{urgency:-1,control:-2,approval:0,curiosity:4,courage:2},'You opened the decision back up to information.']]},
{tag:'CONFLICT',q:'Two strong staff members are in conflict and both want you to pick a side.',c:'Each has a convincing version.',a:[['Decide what seems fairest and tell them how to move forward.',{urgency:3,control:3,approval:0,curiosity:-1,courage:2},'You moved toward resolution quickly.'],['Slow down and understand both experiences first.',{urgency:-2,control:-1,approval:0,curiosity:4,courage:3},'You resisted becoming judge before gathering the story.'],['Put them together and have them work it out.',{urgency:0,control:-1,approval:2,curiosity:1,courage:-1},'You returned responsibility to them, but may have stepped out too early.'],['Tell them they are adults and need to resolve it.',{urgency:1,control:1,approval:1,curiosity:-3,courage:-3},'You escaped the triangle, but also the leadership responsibility.']]},
{tag:'VULNERABILITY',q:'A staff member starts crying during difficult feedback.',c:'The feedback still matters. So does the person in front of you.',a:[['Stop the feedback and reassure them everything is okay.',{urgency:-1,control:-2,approval:4,curiosity:1,courage:-3},'You protected them from distress, but the hard message disappeared.'],['Keep going so the message does not get lost.',{urgency:2,control:3,approval:-2,curiosity:-2,courage:2},'You protected clarity, but gave emotion very little room.'],['Acknowledge the emotion, pause, then ask if they can keep going.',{urgency:-1,control:-1,approval:0,curiosity:3,courage:4},'You stayed with both the emotion and the conversation.'],['End the conversation and reschedule.',{urgency:-1,control:0,approval:3,curiosity:1,courage:-2},'You created space, but delayed the difficult part.']]},
{tag:'COURAGE',q:'A high performer is getting results and burning everyone around them out.',c:'Addressing it could upset someone you do not want to lose.',a:[['Focus on results unless policy is violated.',{urgency:1,control:1,approval:3,curiosity:-1,courage:-4},'You protected performance and avoided the relational cost.'],['Name both their value and the impact of how they are showing up.',{urgency:0,control:0,approval:-1,curiosity:2,courage:4},'You entered the tension directly without making the person the problem.'],['Coach around teamwork without making it too personal.',{urgency:0,control:0,approval:3,curiosity:1,courage:-2},'You moved toward the issue, but softened it enough that it may stay unclear.'],['Ask the team to be more patient.',{urgency:1,control:0,approval:3,curiosity:-1,courage:-3},'You shifted the discomfort away from the high performer.']]},
{tag:'REPAIR',q:'You handled a conversation badly and know it.',c:'You were sharp, cut them off, and watched them shut down.',a:[['Go back, name what you did, and listen to the impact.',{urgency:0,control:-2,approval:-1,curiosity:3,courage:4},'You chose ownership over protecting your image.'],['Apologize and explain how much pressure you were under.',{urgency:1,control:1,approval:2,curiosity:-1,courage:1},'You repaired some, but also protected your intent.'],['Give them space and be warmer next time.',{urgency:-1,control:-1,approval:3,curiosity:0,courage:-3},'You tried to improve the relationship without naming the rupture.'],['Treat them normally so it does not become bigger.',{urgency:0,control:2,approval:2,curiosity:-2,courage:-4},'You protected yourself from awkwardness and left the impact unspoken.']]},
{tag:'VALUES',q:'Compassion and accountability are pulling in opposite directions.',c:'The circumstances are real. The impact on the team is also real.',a:[['Lead with compassion and loosen the expectation.',{urgency:-1,control:-2,approval:4,curiosity:2,courage:-1},'You protected the human, but may have weakened the shared expectation.'],['Hold the expectation consistently so it stays fair.',{urgency:1,control:4,approval:-1,curiosity:-2,courage:2},'You protected consistency and structure.'],['Get curious about context while staying clear about impact.',{urgency:-1,control:-1,approval:0,curiosity:4,courage:4},'You held both truths instead of choosing one.'],['Follow policy exactly so the decision is not personal.',{urgency:1,control:4,approval:0,curiosity:-3,courage:0},'You used policy to reduce ambiguity and personal responsibility.']]}
];
let qi=0,scores={},chosen=[];const keys=['urgency','control','approval','curiosity','courage'];const names={urgency:'Urgency',control:'Control',approval:'Approval',curiosity:'Curiosity',courage:'Courage'};
function resetQuiz(){qi=0;chosen=[];scores={urgency:50,control:50,approval:50,curiosity:50,courage:50}}
function startQuiz(){resetQuiz();show('quizView');header('Before you lead them, meet you.','Eight short moments. Watch what gets louder when responsibility gets uncomfortable.');renderQuiz()}
function renderQuiz(){const q=quiz[qi];$('#quizTag').textContent=q.tag;$('#quizCount').textContent=`${qi+1} / ${quiz.length}`;$('#quizProgress').style.width=`${((qi+1)/quiz.length)*100}%`;$('#quizQuestion').textContent=q.q;$('#quizContext').textContent=q.c;$('#quizAnswers').innerHTML=q.a.map((a,i)=>`<button type="button" data-answer="${i}"><span>${String.fromCharCode(65+i)}</span><b>${a[0]}</b><i>→</i></button>`).join('');updateLoud();$$('[data-answer]').forEach(b=>b.onclick=()=>pickQuiz(+b.dataset.answer))}
function pickQuiz(i){const q=quiz[qi],a=q.a[i];keys.forEach(k=>scores[k]=clamp(scores[k]+a[1][k]*3));chosen.push({q:q.q,a:a[0],note:a[2],delta:a[1]});$$('[data-answer]').forEach((b,n)=>{b.disabled=true;b.classList.toggle('picked',n===i)});updateLoud();setTimeout(()=>{qi++;qi<quiz.length?renderQuiz():results()},260)}
function updateLoud(){keys.forEach(k=>{const n=names[k],v=Math.round(scores[k]);$('#live'+n).textContent=v;$('#bar'+n).style.width=v+'%'})}
function results(){show('resultsView');header('Your starting pattern','Not a type. Not a diagnosis. Just what your eight choices suggested.');const ranked=[...keys].sort((a,b)=>scores[b]-scores[a]),loud=ranked[0],quiet=ranked[ranked.length-1];const summary={urgency:'When responsibility rises, you tend to speed up. Momentum can help. It can also make “act now” louder than “understand first.”',control:'When things feel uncertain, structure and certainty get louder. Useful when direction is needed. Risky when control closes the door to information.',approval:'You notice relationships and how decisions land. That care is a strength. Under pressure, it can become avoiding disappointment or softening what needs clarity.',curiosity:'You make room for information before locking onto a story. Your edge is making sure curiosity eventually becomes a clear leadership move.',courage:'You are willing to move toward discomfort. Your edge is keeping courage connected to curiosity so directness does not become force.'};$('#resultHeadline').textContent=`${names[loud]} got loudest.`;$('#resultSummary').textContent=summary[loud];$('#resultOrbit').innerHTML=ranked.map(k=>`<div class="orbit-chip">${names[k]} <b>${Math.round(scores[k])}</b></div>`).join('');$('#evidenceList').innerHTML=chosen.map((c,i)=>{const strongest=Object.entries(c.delta).sort((a,b)=>Math.abs(b[1])-Math.abs(a[1]))[0];return `<details class="evidence-item"><summary>${i+1}. ${c.a}</summary><div><b>${c.q}</b><br>${c.note}<br><br>Biggest signal: <b>${names[strongest[0]]}</b> ${strongest[1]>=0?'rose':'fell'} in this answer.</div></details>`}).join('');const edges={urgency:['Slow the rush.','Your first rep will practice asking one useful question before solving.','late'],control:['Loosen certainty.','Your first rep will practice separating what you know from what you assume.','feedback'],approval:['Stay kind and stay clear.','Your first rep will practice letting discomfort exist without abandoning the expectation.','late'],curiosity:['Turn curiosity into direction.','Your first rep will practice ending with a clear next move.','late'],courage:['Move toward the hard thing.','Your first rep will practice owning impact instead of waiting for awkwardness to disappear.','mistake']};const e=edges[quiet];$('#practiceEdgeTitle').textContent=e[0];$('#practiceEdgeText').textContent=e[1];$('#practiceFromResult').dataset.scenario=e[2]}

const scenarios={
late:{name:'Taylor',title:'They are late. Again.',setup:'Taylor is 25 minutes late to the team meeting for the third time this month.',known:'The attendance pattern is real.',unknown:'Why the pattern is happening.',open:'I know I am late. I know. Mornings have just been a mess lately.',nudges:[['Get curious','Can you help me understand what has been happening in the mornings?'],['Hold both truths','I want to understand what is happening, and we also need a plan because the team is being impacted.'],['Name the impact','The team has been covering when you are late. I want to talk about that and hear what is going on.'],['Check yourself','I may have walked into this assuming I already knew the whole story.']]},
feedback:{name:'Riley',title:'They feel unheard.',setup:'Riley leaves a team meeting frustrated and asks to speak with you afterward.',known:'Riley challenged the decision publicly.',unknown:'What happened before the challenge.',open:'Honestly? Nobody listens to me around here.',nudges:[['Tell me more','What happened that left you feeling unheard?'],['Own the power','I want to understand whether I shut something down that needed more room.'],['Hold both truths','I want to hear what I missed, and we also need to talk about how we raise concerns in the room.'],['Check the story','I noticed I immediately read your pushback as disrespect. I want to check that assumption.']]},
mistake:{name:'Sam',title:'You shut them down.',setup:'Yesterday you cut Sam off sharply in front of the team. Today they are distant.',known:'You cut Sam off in front of peers.',unknown:'What the moment meant to Sam.',open:'It is fine. We can just move on.',nudges:[['Own it','I want to come back to yesterday. I cut you off in front of everyone, and I do not think I handled that well.'],['Ask about impact','What was that moment like from your side?'],['Skip the defense','I am not going to explain away what I did. I want to understand the impact.'],['Repair + next step','I want to own my part and talk about how we handle disagreement differently next time.']]}}
let current='late',state=null,history=[];
function resetState(){state={turn:0,revealed:false,detail:false,plan:false,guarded:false,owned:false,open:70,clarity:60,trust:68};history=[]}
function addTurn(who,text){const d=document.createElement('div');d.className='turn '+who;d.innerHTML=`<strong>${who==='you'?'YOU':scenarios[current].name}</strong>${text}`;$('#chat').appendChild(d);$('#chat').scrollTop=$('#chat').scrollHeight;history.push({who,text})}
function updateMeters(){[['open','openScore','openBar'],['clarity','clarityScore','clarityBar'],['trust','trustScore','trustBar']].forEach(([k,s,b])=>{$('#'+s).textContent=Math.round(state[k]);$('#'+b).style.width=state[k]+'%'})}
function loadScenario(k){current=k;resetState();const s=scenarios[k];$('#sceneTitle').textContent=s.title;$('#sceneSetup').textContent=s.setup;$('#knownFact').textContent=s.known;$('#unknownFact').textContent=s.unknown;$('#replyInput').value='';$('#replyInput').placeholder=`What would you actually say to ${s.name}?`;$('#chat').innerHTML='';$('#nudgeButtons').innerHTML=s.nudges.map(n=>`<button type="button" data-fill="${n[1].replace(/"/g,'&quot;')}">${n[0]}</button>`).join('');addTurn('them',s.open);$('#coachHeadline').textContent='The room is listening.';$('#coachText').textContent='Your next line changes what becomes easier or harder to say.';$('#coachInterrupt').innerHTML='<small>INTERNAL CHECK</small><b>What are you protecting right now?</b>';$$('[data-scenario]').forEach(b=>b.classList.toggle('active',b.dataset.scenario===k));updateMeters()}
function signals(text){const t=text.toLowerCase();return{question:/\?|help me understand|tell me|what happened|what is happening|what's happening|what was|how did|why/.test(t),impact:/impact|team|cover|late|attendance|expect|need|going forward|next time|plan|responsib|standard/.test(t),care:/sorry|i hear|thank|appreciate|i understand|i get|that sounds/.test(t),ownership:/i was wrong|i messed up|my part|i own|i handled|i cut you off|i assumed|i may have/.test(t),dismiss:/no excuse|not an excuse|just sign|doesn't matter|does not matter|we're done|we are done|figure it out|not my problem/.test(t),solution:/schedule|shift|adjust|brother|tuesday|treatment|coverage|commit|next step|what can you|what would work/.test(t),defense:/but i|because i|you need to understand|i was stressed|i had to/.test(t)}}
function replyLate(s){if(s.dismiss)return{r:'Okay. Then I guess there is not much point explaining.',type:'closed'};if(!state.revealed&&(s.question||s.care||s.ownership)){state.revealed=true;return{r:'My mom started chemo a few weeks ago. I have been the one taking her in before work.',type:'open'};if(!state.revealed&&s.impact)return{r:'I know the team is covering. There is something going on that I have not known how to bring up.',type:'clear'};if(!state.revealed)return{r:'There is more going on than me just not caring about being on time.',type:'neutral'};if(state.revealed&&!state.detail&&(s.question||/chemo|mom|treatment/.test(s.raw))){state.detail=true;return{r:'Tuesdays are the hardest. Her treatment starts early, and I kept thinking I could make both things work without asking anybody for help.',type:'open'};if(s.solution||s.impact){state.plan=true;return{r:'I do not want a free pass. Could we look at a different start time on treatment days and keep the regular expectation the rest of the week?',type:'balanced'};if(s.care)return{r:'Thank you. I was worried telling you would sound like I was making excuses.',type:'open'};return{r:'I know the impact is real. I just need a plan I can actually keep.',type:'balanced'}}
function replyFeedback(s){if(s.dismiss)return{r:'Right. This is why I stopped bringing things up.',type:'closed'};if(!state.revealed&&(s.question||s.ownership||s.care)){state.revealed=true;return{r:'Last week I raised the schedule issue twice. Both times we moved on like I had not said anything.',type:'open'};if(!state.revealed&&s.impact)return{r:'I can own how I came across. I need you to hear that this did not start in that meeting.',type:'clear'};if(!state.revealed)return{r:'I am frustrated because this is not the first time I felt brushed off.',type:'neutral'};if(s.ownership)return{r:'That is what I needed. I do not need you to agree with me every time. I need to know disagreement can be heard.',type:'repair'};if(s.impact||s.solution)return{r:'I can work on how I bring concerns up if we can also make room to actually hear them before they boil over.',type:'balanced'};if(s.question)return{r:'If you had said, “I hear the concern and here is why we are still doing it,” that would have felt completely different.',type:'open'};return{r:'I do not need to win the disagreement. I need to know speaking up is safe.',type:'balanced'}}
function replyMistake(s){if(s.dismiss||s.defense)return{r:'That is exactly why I said it was fine. I did not want another conversation where I had to make your reaction easier for you.',type:'closed'};if(!state.revealed&&(s.ownership||s.question||s.care)){state.revealed=true;state.owned=s.ownership;return{r:'When you cut me off in front of everyone, I felt stupid. After that I was not going to say anything else.',type:s.ownership?'repair':'open'};if(!state.revealed)return{r:'I said it was fine because I did not want another awkward conversation.',type:'neutral'};if(s.ownership)return{r:'Thank you for owning it. I do not need a huge apology. I need to know I can disagree without being embarrassed for it.',type:'repair'};if(s.question)return{r:'What I need is to know disagreement is not the same thing as disrespect.',type:'open'};if(s.solution||s.impact)return{r:'That would help. I can also work on how I raise disagreement if we can keep it from becoming a power fight.',type:'balanced'};return{r:'I know you may not have meant it that way. The impact was still that I shut down.',type:'clear'}}
function respondTo(text){const sig=signals(text);sig.raw=text.toLowerCase();return current==='late'?replyLate(sig):current==='feedback'?replyFeedback(sig):replyMistake(sig)}
function coachFor(type){const map={closed:['The room just got smaller.','Your response made honesty more expensive. You can still repair in the next sentence.'],open:['More information became possible.','Curiosity or ownership opened the conversation. Now listen before you solve.'],clear:['The expectation is visible.','Clarity matters. Add enough curiosity that you are solving the right problem.'],neutral:['The conversation is still open.','Your intent is hard to read. Decide what you want them to understand or tell you.'],balanced:['Two truths stayed in the room.','You did not have to choose between the human and the expectation.'],repair:['That changed the power in the room.','Owning impact without defending intent made repair possible.']};return map[type]||map.neutral}
function adjust(type){const d={closed:{open:-14,clarity:2,trust:-12},open:{open:9,clarity:2,trust:7},clear:{open:0,clarity:9,trust:-1},neutral:{open:1,clarity:1,trust:0},balanced:{open:7,clarity:8,trust:7},repair:{open:9,clarity:5,trust:10}}[type];Object.keys(d).forEach(k=>state[k]=clamp(state[k]+d[k]));updateMeters()}
function send(){const i=$('#replyInput'),text=i.value.trim();if(!text)return;addTurn('you',text);i.value='';const result=respondTo(text);adjust(result.type);state.turn++;setTimeout(()=>{addTurn('them',result.r);const c=coachFor(result.type);$('#coachHeadline').textContent=c[0];$('#coachText').textContent=c[1];$('#unknownFact').textContent=state.revealed?(current==='late'?'How you lead now that context changed.':current==='feedback'?'What repair and voice both require.':'What Sam needs from you next.'):(scenarios[current].unknown);$('#coachInterrupt').innerHTML=state.turn===1?'<small>INTERNAL CHECK</small><b>Did you enter to understand, correct, defend, or repair?</b>':state.turn===2?'<small>NOTICE</small><b>New information does not erase accountability. It changes what good leadership must account for.</b>':'<small>STAY WITH IT</small><b>Do not rush to end the discomfort. Finish the leadership move.</b>'},220)}
function rewind(){if(history.length<2)return;loadScenario(current)}

$('#brandHome').onclick=home;$('#restartBtn').onclick=home;$('#startQuizBtn').onclick=startQuiz;$('#startQuizBtn2').onclick=startQuiz;$('#skipToPracticeBtn').onclick=()=>practice('late');$('#practiceFromResult').onclick=e=>practice(e.currentTarget.dataset.scenario||'late');$$('.nav-btn').forEach(b=>b.onclick=()=>b.dataset.nav==='home'?home():b.dataset.nav==='practice'?practice('late'):moments());$$('[data-jump="practice"]').forEach(b=>b.onclick=()=>practice(b.dataset.scenario||'late'));$$('[data-jump="moments"]').forEach(b=>b.onclick=moments);$$('[data-scenario]').forEach(b=>b.onclick=()=>practice(b.dataset.scenario));$('#sayBtn').onclick=send;$('#replyInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}});document.addEventListener('click',e=>{const b=e.target.closest('[data-fill]');if(b){$('#replyInput').value=b.dataset.fill;$('#replyInput').focus()}});$('#rewindBtn').onclick=rewind;$('#resetSceneBtn').onclick=()=>loadScenario(current);$('#medMoment').onclick=()=>{$('#medPreview').hidden=false;$('#medPreview').scrollIntoView({behavior:'smooth',block:'start'})};$('#closeMedPreview').onclick=()=>{$('#medPreview').hidden=true};home();
})();