(()=>{
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const views=['homeView','quizView','resultsView','practiceView','momentsView'];
const clamp=n=>Math.max(0,Math.min(100,n));
function show(id){views.forEach(v=>$('#'+v).hidden=v!==id);$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.nav===id.replace('View','')));window.scrollTo({top:0,behavior:'smooth'});}
function header(t,s){$('#pageTitle').textContent=t;$('#pageSub').textContent=s;}
function home(){show('homeView');header('Welcome to the messy middle.','New supervisors don\'t need another slideshow. They need somewhere to practice.');}
function moments(){show('momentsView');header('Supervisor Moments','Real responsibility. Human reactions. Practice before the hard moment is live.');}

const quiz=[
{tag:'POWER',q:'A staff member challenges your decision in front of the whole team.',c:'Everyone looks at you. What pulls at you first?',a:[
['Explain why the decision makes sense.',{urgency:2,control:4,approval:0,curiosity:-2,courage:1},'You moved toward certainty and authority.'],
['Ask what they are seeing that you may be missing.',{urgency:0,control:-1,approval:0,curiosity:4,courage:3},'You made room for information without giving up your role.'],
['Say you will talk privately later.',{urgency:1,control:2,approval:2,curiosity:0,courage:0},'You contained the moment, but postponed the disagreement.'],
['Move the meeting along and circle back another day.',{urgency:1,control:1,approval:3,curiosity:-1,courage:-3},'You lowered discomfort, but delayed the hard part.']]},
{tag:'ACCOUNTABILITY',q:'Someone you supervise is late. Again.',c:'The team has had to cover. You already have the corrective action form open.',a:[
['Start with the documented pattern and consequence.',{urgency:3,control:4,approval:-1,curiosity:-3,courage:2},'You prioritized structure and consequence before context.'],
['Name the pattern and impact, then ask what is happening.',{urgency:0,control:0,approval:0,curiosity:4,courage:4},'You held accountability and curiosity at the same time.'],
['Give one more chance because life is hard.',{urgency:-1,control:-1,approval:4,curiosity:1,courage:-3},'You protected the relationship from discomfort, but softened the expectation.'],
['Tell them the team is tired of picking up their slack.',{urgency:3,control:3,approval:-2,curiosity:-4,courage:1},'You made impact visible, but used blame to do it.']]},
{tag:'ARMOR',q:'Halfway through a meeting, you realize your plan may be wrong.',c:'You are the person who recommended it.',a:[
['Say what changed your thinking and adjust.',{urgency:0,control:-2,approval:-1,curiosity:3,courage:4},'You tolerated being visibly wrong and changed course.'],
['Stick with it until you can reconsider privately.',{urgency:1,control:4,approval:1,curiosity:-3,courage:-2},'You protected authority and certainty in the moment.'],
['Explain your original reasoning so everyone understands.',{urgency:1,control:2,approval:2,curiosity:-1,courage:0},'You protected your intent before fully addressing the new information.'],
['Ask the room what they think before deciding.',{urgency:-1,control:-2,approval:0,curiosity:4,courage:2},'You opened the decision back up to information.']]},
{tag:'CONFLICT',q:'Two strong staff members are in conflict and both want you to pick a side.',c:'Each has a convincing version.',a:[
['Decide what seems fairest and tell them how to move forward.',{urgency:3,control:3,approval:0,curiosity:-1,courage:2},'You moved toward resolution quickly.'],
['Slow down and understand both experiences first.',{urgency:-2,control:-1,approval:0,curiosity:4,courage:3},'You resisted becoming judge before gathering the story.'],
['Put them together and have them work it out.',{urgency:0,control:-1,approval:2,curiosity:1,courage:-1},'You returned responsibility to them, but may have stepped out too early.'],
['Tell them they are adults and need to resolve it.',{urgency:1,control:1,approval:1,curiosity:-3,courage:-3},'You escaped the triangle, but also the leadership responsibility.']]},
{tag:'VULNERABILITY',q:'A staff member starts crying during difficult feedback.',c:'The feedback still matters. So does the person in front of you.',a:[
['Stop the feedback and reassure them everything is okay.',{urgency:-1,control:-2,approval:4,curiosity:1,courage:-3},'You protected them from distress, but the hard message disappeared.'],
['Keep going so the message does not get lost.',{urgency:2,control:3,approval:-2,curiosity:-2,courage:2},'You protected clarity, but gave emotion very little room.'],
['Acknowledge the emotion, pause, then ask if they can keep going.',{urgency:-1,control:-1,approval:0,curiosity:3,courage:4},'You stayed with both the emotion and the conversation.'],
['End the conversation and reschedule.',{urgency:-1,control:0,approval:3,curiosity:1,courage:-2},'You created space, but delayed the difficult part.']]},
{tag:'COURAGE',q:'A high performer is getting results and burning everyone around them out.',c:'Addressing it could upset someone you really do not want to lose.',a:[
['Focus on results unless policy is violated.',{urgency:1,control:1,approval:3,curiosity:-1,courage:-4},'You protected performance and avoided the relational cost.'],
['Name both their value and the impact of how they are showing up.',{urgency:0,control:0,approval:-1,curiosity:2,courage:4},'You entered the tension directly without making the person the problem.'],
['Coach around teamwork without making it too personal.',{urgency:0,control:0,approval:3,curiosity:1,courage:-2},'You moved toward the issue, but softened it enough that it may stay unclear.'],
['Ask the team to be more patient.',{urgency:1,control:0,approval:3,curiosity:-1,courage:-3},'You shifted the discomfort away from the high performer.']]},
{tag:'REPAIR',q:'You handled a conversation badly and know it.',c:'You were sharp, cut them off, and watched them shut down.',a:[
['Go back, name what you did, and listen to the impact.',{urgency:0,control:-2,approval:-1,curiosity:3,courage:4},'You chose ownership over protecting your image.'],
['Apologize and explain how much pressure you were under.',{urgency:1,control:1,approval:2,curiosity:-1,courage:1},'You repaired some, but also protected your intent.'],
['Give them space and be warmer next time.',{urgency:-1,control:-1,approval:3,curiosity:0,courage:-3},'You tried to improve the relationship without naming the rupture.'],
['Treat them normally so it does not become bigger.',{urgency:0,control:2,approval:2,curiosity:-2,courage:-4},'You protected yourself from awkwardness and left the impact unspoken.']]},
{tag:'VALUES',q:'Compassion and accountability are pulling in opposite directions.',c:'The circumstances are real. The impact on the team is also real.',a:[
['Lead with compassion and loosen the expectation.',{urgency:-1,control:-2,approval:4,curiosity:2,courage:-1},'You protected the human, but may have weakened the shared expectation.'],
['Hold the expectation consistently so it stays fair.',{urgency:1,control:4,approval:-1,curiosity:-2,courage:2},'You protected consistency and structure.'],
['Get curious about context while staying clear about impact.',{urgency:-1,control:-1,approval:0,curiosity:4,courage:4},'You held both truths instead of choosing one.'],
['Follow policy exactly so the decision is not personal.',{urgency:1,control:4,approval:0,curiosity:-3,courage:0},'You used policy to reduce ambiguity and personal responsibility.']]}
];
let qi=0,scores={},chosen=[];const keys=['urgency','control','approval','curiosity','courage'];const names={urgency:'Urgency',control:'Control',approval:'Approval',curiosity:'Curiosity',courage:'Courage'};
function resetQuiz(){qi=0;chosen=[];scores={urgency:50,control:50,approval:50,curiosity:50,courage:50};}
function startQuiz(){resetQuiz();show('quizView');header('What gets loud in you?','Eight real supervisor moments. No pass or fail. Just patterns.');renderQuiz();}
function renderQuiz(){const q=quiz[qi];$('#quizTag').textContent=q.tag;$('#quizCount').textContent=`${qi+1} / ${quiz.length}`;$('#quizProgress').style.width=`${((qi+1)/quiz.length)*100}%`;$('#quizQuestion').textContent=q.q;$('#quizContext').textContent=q.c;$('#quizAnswers').innerHTML=q.a.map((a,i)=>`<button type="button" data-answer="${i}"><span>${String.fromCharCode(65+i)}</span><b>${a[0]}</b><i>→</i></button>`).join('');updateLoud();$$('[data-answer]').forEach(b=>b.onclick=()=>pickQuiz(+b.dataset.answer));}
function pickQuiz(i){const q=quiz[qi],a=q.a[i];keys.forEach(k=>scores[k]=clamp(scores[k]+a[1][k]*3));chosen.push({q:q.q,a:a[0],note:a[2],delta:a[1]});$$('[data-answer]').forEach((b,n)=>{b.disabled=true;b.classList.toggle('picked',n===i)});updateLoud();setTimeout(()=>{qi++;qi<quiz.length?renderQuiz():results();},300);}
function updateLoud(){keys.forEach(k=>{const n=names[k],v=Math.round(scores[k]);$('#live'+n).textContent=v;$('#bar'+n).style.width=v+'%';});}
function results(){show('resultsView');header('Your leadership pattern','Not a label. A snapshot of what got louder across eight choices.');const ranked=[...keys].sort((a,b)=>scores[b]-scores[a]),loud=ranked[0],quiet=ranked[ranked.length-1];const summary={urgency:'When responsibility rises, you tend to speed up. That can create momentum, but it can also make “act now” louder than “understand first.”',control:'When things feel uncertain, structure and certainty get louder. Useful when the room needs direction. Risky when control closes the door to information.',approval:'You notice relationships and how your decisions land. That care is a strength. Under pressure, it can become avoiding disappointment or softening what needs clarity.',curiosity:'You make room for information before locking onto a story. Your edge is making sure curiosity eventually becomes a clear leadership move.',courage:'You are willing to move toward discomfort. Your edge is keeping courage connected to curiosity so directness does not become force.'};$('#resultHeadline').textContent=`${names[loud]} got loudest.`;$('#resultSummary').textContent=summary[loud];$('#resultOrbit').innerHTML=ranked.map(k=>`<div class="orbit-chip">${names[k]} <b>${Math.round(scores[k])}</b></div>`).join('');$('#evidenceList').innerHTML=chosen.map((c,i)=>{const strongest=Object.entries(c.delta).sort((a,b)=>Math.abs(b[1])-Math.abs(a[1]))[0];return `<details class="evidence-item"><summary>${i+1}. ${c.a}</summary><div><b>${c.q}</b><br>${c.note}<br><br>Biggest shift: <b>${names[strongest[0]]}</b> ${strongest[1]>=0?'got louder':'got quieter'}.</div></details>`;}).join('');const edge={urgency:['Slow the rush.','Practice asking one useful question before solving.'],control:['Loosen certainty.','Practice separating what you know from what you are assuming.'],approval:['Stay kind and stay clear.','Practice letting someone be disappointed without abandoning the expectation.'],curiosity:['Turn curiosity into direction.','Practice ending the conversation with a clear next step.'],courage:['Move toward the hard thing.','Practice entering the conversation sooner instead of waiting for comfort.']};$('#practiceEdgeTitle').textContent=edge[quiet][0];$('#practiceEdgeText').textContent=edge[quiet][1];}

const scenarios={
late:{name:'Taylor',title:"They're late. Again.",setup:'Taylor is 25 minutes late to the team meeting for the third time this month.',known:'The attendance pattern is real.',unknown:'Why the pattern is happening.',open:"I know I'm late. I know. Mornings have just been a mess lately.",nudges:[['Get curious','Can you help me understand what has been happening in the mornings?'],['Hold both truths','I want to understand what is happening, and we also need a plan because the team is being impacted.'],['Name the impact','The team has been covering when you are late. I want to talk about that and hear what is going on.'],['Check yourself','I may have walked into this assuming I already knew the whole story.']],replies:{curious:["My mom started chemo a few weeks ago. I've been the one taking her in before work.","Tuesdays are the worst. I kept thinking I could make the timing work without making it everybody else's problem.","I can ask my brother to take one morning, but not all of them. Could we look at a different start time on treatment days?","I don't want a free pass. I need a plan I can actually keep."],balanced:["Okay. That's fair. My mom started chemo, and I've been taking her in before work. I should've told you sooner.","I know the team is getting stuck with it too. I hate that. I just haven't known what to ask for.","Could we look at Tuesdays differently and keep the regular expectation the rest of the week?","That feels doable. I can communicate ahead of time instead of hoping I make it."],clear:["I hear the expectation. I just feel like you've already decided why I'm late.","There's something going on that I haven't known how to bring up.","If we're going to make a plan, can I explain the actual schedule first?"],connected:["Thanks. I wasn't sure if I should tell you.","It's my mom. She has chemo in the mornings and I'm taking her.","I know that doesn't erase the impact. I just didn't want people thinking I was asking for special treatment."],dismissive:["...okay.","Then I guess there isn't much point explaining.","Just give me whatever I need to sign."],neutral:["I don't really know what you want me to say.","There's more going on than me not caring about being on time.","Can I explain before we decide what happens next?"]}},
feedback:{name:'Riley',title:'They feel unheard.',setup:'Riley leaves a team meeting frustrated and asks to speak with you afterward.',known:'Riley challenged the decision publicly.',unknown:'What happened before the challenge.',open:'Honestly? Nobody listens to me around here.',nudges:[['Tell me more','What happened that left you feeling unheard?'],['Own the power','I want to understand whether I shut something down that needed more room.'],['Hold both truths','I want to hear what I missed, and we also need to talk about how we raise concerns in the room.'],['Check the story','I noticed I immediately read your pushback as disrespect. I want to check that assumption.']],replies:{curious:["Last week I raised the schedule issue twice. Both times everyone moved on like I hadn't said anything.","I'm not asking you to agree with me. I want to know disagreement actually gets heard.","If you'd said you heard the concern and explained the decision, that would've felt completely different."],balanced:["I can own that I came in hot. I also tried to raise it twice before today.","That's what I need. I can work on how I bring concerns up if we can make room to actually hear them.","I don't need to win every disagreement. I need to know speaking up is safe."],clear:["I can hear the expectation. But we're talking about my reaction before we're talking about what happened.","I can own how I came across. I need you to own that I tried to raise it before it blew up."],connected:["Thank you. Mostly I felt invisible.","I don't need you to fix everything. I need to know disagreement isn't going to cost me."],dismissive:["Right. This is why I stopped bringing things up.","Got it. I'll keep my head down next time."],neutral:["I'm frustrated because this isn't the first time.","I don't think you're hearing what I'm trying to say."]}},
mistake:{name:'Sam',title:'You messed up.',setup:'Yesterday you cut Sam off sharply in front of the team. Today they are distant.',known:'You shut the conversation down publicly.',unknown:'The impact your authority had in the room.',open:"It's fine. We can just move on.",nudges:[['Own it','I don\'t think it was fine. I cut you off in front of everyone, and I want to own that.'],['Ask impact','What was that like from your side?'],['No defense','I was stressed, but that doesn\'t excuse how I handled you.'],['Repair','I want to understand what I need to do differently next time.']],replies:{curious:["When you cut me off, I felt stupid. After that I wasn't going to say anything else.","You're my supervisor. When you shut me down, everyone notices.","What I need is to know I can disagree without getting embarrassed for it."],balanced:["I appreciate you owning it. Yeah, it embarrassed me.","I also could've brought my disagreement differently. But I need to know I can challenge an idea without it turning into me challenging you.","If you need to stop me next time, just do it without making me feel small."],clear:["I understand you wanted to keep the meeting moving. The impact was still that I felt shut down.","If we're talking expectations, I need one too: correct me without embarrassing me."],connected:["Thank you for saying that. I wasn't sure you even noticed.","I don't need a huge apology. I need it not to happen again."],dismissive:["Sure. It's fine.","I'd rather just leave it alone."],neutral:["I said it's fine because I didn't want another awkward conversation.","What happened yesterday is still sitting with me."]}}
};
let scene='late',turn=0,history=[],room={open:70,clarity:60,trust:68};
function classify(text){const t=text.toLowerCase();if(/tough it out|suck it up|get over it|no excuses|not my problem|whatever/.test(t))return'dismissive';const q=/understand|tell me|what happened|what's going|what is going|help me|what was|can you|could you|why|\?/.test(t),care=/sorry|i own|i hear|thank|appreciate|my part|doesn't excuse|does not excuse/.test(t),clear=/impact|need|expect|responsib|going forward|important|team|plan|commit|attendance/.test(t);if((q||care)&&clear)return'balanced';if(q)return'curious';if(care)return'connected';if(clear)return'clear';return'neutral';}
function replyFor(type){const arr=scenarios[scene].replies[type]||scenarios[scene].replies.neutral;return arr[Math.min(turn,arr.length-1)];}
function coachFor(type){return{dismissive:['The door just narrowed.','Your response made honesty more expensive. You can still repair in the very next sentence.'],curious:['You opened the room.','Curiosity gave you information. It did not erase accountability.'],balanced:['You held two truths.','You made room for the human context and kept responsibility visible.'],connected:['The temperature dropped.','Connection increased. Now make sure the hard thing does not disappear.'],clear:['The expectation is visible.','Clarity rose. The next move is checking whether you are solving the right problem.'],neutral:['Your intent is hard to read.','What do you actually want them to understand or tell you?']}[type];}
function adjust(type){const d={dismissive:[-14,5,-12],curious:[12,2,10],balanced:[10,12,11],connected:[9,0,10],clear:[-1,11,-1],neutral:[1,1,0]}[type];room.open=clamp(room.open+d[0]);room.clarity=clamp(room.clarity+d[1]);room.trust=clamp(room.trust+d[2]);updateRoom();}
function updateRoom(){$('#openScore').textContent=Math.round(room.open);$('#clarityScore').textContent=Math.round(room.clarity);$('#trustScore').textContent=Math.round(room.trust);$('#openBar').style.width=room.open+'%';$('#clarityBar').style.width=room.clarity+'%';$('#trustBar').style.width=room.trust+'%';}
function addTurn(who,text){const d=document.createElement('div');d.className='turn '+who;d.innerHTML=`<strong>${who==='you'?'YOU':scenarios[scene].name}</strong>${text}`;$('#chat').appendChild(d);$('#chat').scrollTop=$('#chat').scrollHeight;return d;}
function loadScenario(k){scene=k;turn=0;history=[];room={open:70,clarity:60,trust:68};const s=scenarios[k];$('#sceneTitle').textContent=s.title;$('#sceneSetup').textContent=s.setup;$('#knownFact').textContent=s.known;$('#unknownFact').textContent=s.unknown;$('#chat').innerHTML='';addTurn('them',s.open);$('#nudgeButtons').innerHTML=s.nudges.map(n=>`<button type="button" data-fill="${n[1].replace(/"/g,'&quot;')}">${n[0]}</button>`).join('');$('#coachHeadline').textContent='The room is listening.';$('#coachText').textContent='Your words change what becomes easier or harder for the other person to say next.';$('#coachInterrupt').innerHTML='<small>INTERNAL CHECK</small><b>What are you protecting right now?</b>';$$('[data-scenario]').forEach(b=>b.classList.toggle('active',b.dataset.scenario===k));updateRoom();bindNudges();}
function bindNudges(){$$('[data-fill]').forEach(b=>b.onclick=()=>{$('#replyInput').value=b.dataset.fill;$('#replyInput').focus();});}
function send(){const input=$('#replyInput'),text=input.value.trim();if(!text)return;const type=classify(text);const you=addTurn('you',text);history.push({node:you,text,type,room:{...room}});input.value='';adjust(type);const [h,c]=coachFor(type);$('#coachHeadline').textContent=h;$('#coachText').textContent=c;$('#coachInterrupt').innerHTML=type==='dismissive'?'<small>OHHH.</small><b>The guard went up. Want to repair?</b>':type==='balanced'?'<small>NOTICE THIS</small><b>You kept the person and the expectation in the same room.</b>':type==='clear'?'<small>WAIT.</small><b>Clear is good. Do you have the whole story yet?</b>':'<small>INTERNAL CHECK</small><b>What are you protecting right now?</b>';setTimeout(()=>{const them=addTurn('them',replyFor(type));history.push({node:them,text:replyFor(type),type:'them'});turn++;if(turn===1&&['curious','balanced','connected'].includes(type))$('#unknownFact').textContent='How you respond now that context changed.';},320);}
function practice(k='late'){show('practiceView');header('Conversation Lab','Type what you would really say. The other person will respond to the move you make.');loadScenario(k);}
function rewind(){if(!history.length)return;while(history.length){const h=history.pop();h.node.remove();if(h.type!=='them'){room={...h.room};updateRoom();break;}}turn=Math.max(0,turn-1);$('#coachHeadline').textContent='Rewound.';$('#coachText').textContent='Try a different move. Repair and replay are part of leadership too.';}

function boot(){
$('#brandHome').onclick=home;$('#restartBtn').onclick=home;$('#startQuizBtn').onclick=startQuiz;$('#startQuizBtn2').onclick=startQuiz;$('#skipToPracticeBtn').onclick=()=>practice('late');$('#practiceFromResult').onclick=()=>practice('late');
$$('.nav-btn').forEach(b=>b.onclick=()=>b.dataset.nav==='home'?home():b.dataset.nav==='practice'?practice('late'):moments());
$$('[data-jump]').forEach(b=>b.onclick=()=>b.dataset.jump==='practice'?practice(b.dataset.scenario||'late'):moments());
$$('[data-scenario]').forEach(b=>b.onclick=()=>practice(b.dataset.scenario));
$('#sayBtn').onclick=send;$('#replyInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send();}});$('#rewindBtn').onclick=rewind;$('#resetSceneBtn').onclick=()=>loadScenario(scene);
$('#medMoment').onclick=()=>{$('#medPreview').hidden=false;$('#medPreview').scrollIntoView({behavior:'smooth',block:'start'});};$('#closeMedPreview').onclick=()=>$('#medPreview').hidden=true;
home();
}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',boot):boot();
})();