const scenarios={
  late:{title:"They're late.<br><em>AGAIN.</em>",name:'Taylor',setup:'Taylor is 25 minutes late to the team meeting again. You pull them aside.',bubble:"I know what you're thinking.<br>Just hear me out, okay?",opening:"I know I'm late. I just... mornings have been rough lately.",coach:'Stay connected and address the issue.',suggestions:["I notice you've been late a few times. Can you help me understand what's going on?","This is impacting the team, and I also want to understand what you're dealing with.","I want to talk about the lateness without making assumptions. What's happening?"],reply:{curious:"Taylor's shoulders loosen. “My mom's been having health problems. I've been helping her in the mornings and I didn't know how to bring it up.”",balanced:"Taylor nods. “Yeah. I know it affects everyone. My mom's been sick and mornings have been hard. Can we figure something out?”",clear:"Taylor looks down. “I know. I'm not trying to make everyone pick up my slack.”",defensive:"Taylor crosses their arms. “Okay. I said I know I'm late.”",avoidant:"Taylor nods quickly. “Thanks.” The problem is still sitting in the room with both of you."}},
  feedback:{title:'They feel<br><em>UNHEARD.</em>',name:'Riley',setup:'Riley walks into your office frustrated after a team meeting and says nobody listens to them.',bubble:'Why do I even speak up<br>if everyone just moves on?',opening:'Honestly? Nobody listens to me around here. I bring things up and it is like I never said anything.',coach:'Curiosity before defense. Understand the experience before explaining it.',suggestions:["Can you walk me through a time you felt ignored?","I want to understand what has made it feel that way.","That sounds frustrating. Tell me what happened in the meeting from your perspective."],reply:{curious:'Riley pauses. “Last week I raised the schedule issue twice, and both times the conversation just moved on.”',balanced:'Riley nods. “Exactly. I want us to solve things, but I need to know my input actually lands somewhere.”',clear:'Riley says, “I can give examples. I just do not want this to turn into me having to prove I deserve to be heard.”',defensive:'Riley leans back. “See? I say I do not feel heard and now I have to defend why.”',avoidant:'Riley shrugs. “Never mind. It is not worth it.”'}},
  mistake:{title:'You messed<br><em>THAT UP.</em>',name:'Sam',setup:'Yesterday you cut Sam off in front of the team. Today they are quiet and distant.',bubble:"It's fine.<br>We can just move on.",opening:"It's fine. We can just move on.",coach:'Repair starts with ownership, not an explanation of your intent.',suggestions:["I do not want to just move on. I cut you off yesterday, and that was not okay.","I realized I dismissed what you were saying in front of everyone. I am sorry.","I want to own how I handled that meeting before I ask anything from you."],reply:{curious:'Sam says, “I was embarrassed. It felt like there was not room for me to disagree with you.”',balanced:'Sam looks at you for a second. “I appreciate you saying that. I felt dismissed, and it really did bother me.”',clear:'Sam gives a small nod. “Okay. I needed you to know it did not feel respectful.”',defensive:'Sam closes off. “I know you did not mean it that way. That does not really change how it felt.”',avoidant:'Sam says, “Sure.” The distance stays exactly where it was.'}}
};

const rooms={
  armor:{title:'🛡️ Armor Check',text:'When leadership gets uncomfortable, what do you reach for first?',items:['Getting overly certain','Fixing instead of listening','Humor to dodge discomfort','Control','Silence or avoidance'],prompt:'Notice it without judging it. Armor usually protected you somewhere. The practice is deciding whether you still need it here.'},
  rumble:{title:'🥊 The Rumble Room',text:'Pick the conversation you keep rehearsing in your head.',items:['Giving hard feedback','Naming tension on the team','Holding a boundary','Disagreeing with someone you respect'],prompt:'Start with what you observe, what matters, and what you are genuinely curious about.'},
  story:{title:'🔎 The Story Check',text:'Your brain is fast. Sometimes too fast.',items:['What did I actually observe?','What meaning did I attach to it?','What else could be true?','What question would give me real information?'],prompt:'Facts first. Stories second. Curiosity before certainty.'},
  values:{title:'🧪 Values Lab',text:'Values are easy on the calm days. Pressure is where they become visible.',items:['Which value do I want people to experience from me?','What would that value look like as a behavior?','What will it cost me to live it here?'],prompt:'Choose the behavior, not just the word.'},
  repair:{title:'🧰 Repair Shop',text:'You do not have to be perfect. You do have to come back.',items:['Name what you did','Own the impact','Skip the defensive explanation','Ask what is needed now'],prompt:'Repair is leadership too.'},
  arena:{title:'🥊 The Arena',text:'This is the role-play room. Choose a situation at the top and say what you would really say.',items:['Try a response','Watch what changes','Notice your impact','Try again'],prompt:'No perfect answer. Just practice.'}
};

let current='late';
let scores={connection:72,clarity:65,courage:48};
let notebook=JSON.parse(localStorage.getItem('leadershipLabNotebookV2')||'[]');
const $=s=>document.querySelector(s);
function esc(v){return v.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function setScores(){['connection','clarity','courage'].forEach(k=>{const n=Math.max(5,Math.min(100,Math.round(scores[k])));$('#'+k+'Meter').style.width=n+'%';$('#'+k+'Score').textContent=n;});}
function classify(text){const t=text.toLowerCase();let type='neutral',d={connection:2,clarity:2,courage:2};if(/help me understand|tell me|what happened|what's going|what is going|walk me through|want to understand|what do you need/.test(t)){type='curious';d={connection:10,clarity:3,courage:5}}if(/sorry|i own|i realize|i realised|i hear|that sounds|i can see|i appreciate/.test(t)){type='connected';d.connection+=9;d.courage+=5}if(/impact|need to|we need|expect|on time|responsib|important|agreement/.test(t)){type=(type==='curious'||type==='connected')?'balanced':'clear';d.clarity+=12;d.courage+=8}if(/you always|you never|excuse|unacceptable|why didn't|why did you|but you/.test(t)){type='defensive';d={connection:-14,clarity:5,courage:1}}if(/don't worry|no big deal|forget it|move on|it's fine|its fine/.test(t)){type='avoidant';d={connection:2,clarity:-10,courage:-9}}return {type,d}}
function updateAvatar(){const c=scores.connection;if(c>76){$('#avatarMouth').setAttribute('d','M108 154 Q130 172 152 154');$('#character').style.transform='translateY(0) rotate(0deg)';}else if(c<50){$('#avatarMouth').setAttribute('d','M109 164 Q130 151 151 164');$('#character').style.transform='translateY(2px) rotate(-2deg)';}else{$('#avatarMouth').setAttribute('d','M108 157 Q130 164 151 155');$('#character').style.transform='translateY(0)';}}
function loadScenario(key){current=key;scores={connection:72,clarity:65,courage:48};const s=scenarios[key];$('#sceneTitle').innerHTML=s.title;$('#sceneSetup').textContent=s.setup;$('#characterBubble').innerHTML=s.bubble;$('#replyInput').placeholder=`Type what you would say to ${s.name}...`;$('#coachText').textContent=s.coach;$('#chat').innerHTML=`<div class="chat-bubble them"><strong>${s.name}:</strong> ${esc(s.opening)}</div>`;$('#winText').textContent='You showed up. That is a win.';document.querySelectorAll('.scenario-pill[data-scenario]').forEach(b=>b.classList.toggle('active',b.dataset.scenario===key));setScores();updateAvatar();}
function respond(text){if(!text.trim())return;const {type,d}=classify(text);Object.keys(scores).forEach(k=>scores[k]+=d[k]);const s=scenarios[current];$('#chat').insertAdjacentHTML('beforeend',`<div class="chat-bubble you">${esc(text)}</div>`);$('#replyInput').value='';setScores();updateAvatar();$('#characterBubble').textContent='...';setTimeout(()=>{const reply=s.reply[type]||s.reply.curious;$('#chat').insertAdjacentHTML('beforeend',`<div class="chat-bubble them"><strong>${s.name}:</strong> ${esc(reply)}</div>`);$('#characterBubble').textContent=reply.replace(/^.*?[“"]|[”"]$/g,'').slice(0,90);$('#chat').scrollTop=$('#chat').scrollHeight;const coach={curious:'Curiosity opened the door. Stay with it before you solve.',connected:'You made room for the human. Check whether clarity needs a seat too.',balanced:'You are holding connection and accountability together. That is the practice.',clear:'Clear matters. Make sure the person still has enough room to be honest.',defensive:'The room tightened. What would happen if you traded certainty for curiosity?',avoidant:'Comfort increased, but the real issue did not move.',neutral:'Notice what your words invited more of: honesty, caution, clarity, or distance.'};$('#coachText').textContent=coach[type];$('#winText').textContent=type==='balanced'?'You held the human and the hard thing at once.':type==='curious'?'You stayed curious when certainty would have been easier.':type==='defensive'?'You noticed tension. Now you get another rep.':'You practiced instead of performing.';},500)}

$('#replyForm').addEventListener('submit',e=>{e.preventDefault();respond($('#replyInput').value)});
document.querySelectorAll('[data-fill]').forEach(b=>b.addEventListener('click',()=>{$('#replyInput').value=b.dataset.fill;$('#replyInput').focus()}));
document.querySelectorAll('.scenario-pill[data-scenario]').forEach(b=>b.addEventListener('click',()=>loadScenario(b.dataset.scenario)));
$('#randomScenario').addEventListener('click',()=>{const keys=Object.keys(scenarios).filter(k=>k!==current);loadScenario(keys[Math.floor(Math.random()*keys.length)])});

const roomDialog=$('#roomDialog'),roomDialogContent=$('#roomDialogContent');
function openRoom(key){const r=rooms[key];if(key==='arena'){window.scrollTo({top:0,behavior:'smooth'});return;}roomDialogContent.innerHTML=`<h2>${r.title}</h2><p>${r.text}</p><ul>${r.items.map(i=>`<li>${i}</li>`).join('')}</ul><div class="coach-note"><span>TRY THIS ↝</span><p>${r.prompt}</p></div>`;roomDialog.showModal();}
document.querySelectorAll('[data-room]').forEach(b=>b.addEventListener('click',()=>openRoom(b.dataset.room)));
$('#closeDialog').addEventListener('click',()=>roomDialog.close());

function renderNotebook(){$('#notebookCount').textContent=notebook.length;$('#notebookEntries').innerHTML=notebook.length?notebook.map(n=>`<div class="notebook-entry"><strong>${esc(n.scenario)}</strong><p>${esc(n.note)}</p><small>${esc(n.date)}</small></div>`).join(''):'<p>No reps saved yet. Try a conversation, then save the insight you want to keep.</p>';}
$('#saveInsight').addEventListener('click',()=>{notebook.unshift({scenario:scenarios[current].name+' scenario',note:$('#coachText').textContent,date:new Date().toLocaleDateString()});notebook=notebook.slice(0,20);localStorage.setItem('leadershipLabNotebookV2',JSON.stringify(notebook));renderNotebook();$('#saveInsight').textContent='✓ SAVED TO NOTEBOOK';setTimeout(()=>$('#saveInsight').textContent='☆ SAVE THIS REP',1200)});
$('#notebookBtn').addEventListener('click',()=>{$('#notebookDialog').showModal()});
$('#closeNotebook').addEventListener('click',()=>$('#notebookDialog').close());
renderNotebook();loadScenario('late');